vars:
  OS: $(uname -s)
  ARCH: $(uname -m)
tasks:
  printos:
    cmds:
      - echo ${OS} ${ARCH}
  print-goenv:
    pres:
      - printos
    vars:
      GOPATH: $(go env GOPATH)
      GOBIN: $(go env GOROOT)
    cmds:
      - echo GOPATH ${GOPATH}
      - echo GOROOT ${GOROOT}
  cron-printos:
    cron: "*/1 * * * *"
    cmds:
      - echo ${OS} ${ARCH}