vars:
  OS: $(uname -s)
  ARCH: $(uname -m)
tasks:
  printos:
    cmds:
      - echo ${OS} ${ARCH}
  print-goenv:
    pres:
      - printos
    vars:
      GOPATH: $(go env GOPATH)
    cmds:
      - echo ${GOPATH}