[package]
name = "runo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.200.0"
anyhow = "1.0.72"
axum = "0.6.20"
tokio = { version = "1.29.1", features = ["full"] }
